<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $misiones = [
            // ─── DIARIAS ────────────────────────────────────────────────
            [
                'nombre'           => 'Primer paso del día',
                'descripcion'      => 'Da tus primeros 100 metros del día. ¡El movimiento empieza con un solo paso!',
                'metros_requeridos' => 100,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 15,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Paseo matutino',
                'descripcion'      => 'Camina 250 metros para empezar el día con energía.',
                'metros_requeridos' => 250,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 20,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Media hora andando',
                'descripcion'      => 'Recorre al menos 750 metros. ¡Un paseo refrescante!',
                'metros_requeridos' => 750,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 35,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'El kilómetro diario',
                'descripcion'      => 'Completa 1 kilómetro caminando hoy. ¡Tu cuerpo te lo agradecerá!',
                'metros_requeridos' => 1000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 50,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Explorador urbano',
                'descripcion'      => 'Camina 1,5 kilómetros explorando las calles de tu ciudad.',
                'metros_requeridos' => 1500,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 65,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Ruta al parque',
                'descripcion'      => 'Recorre 2 kilómetros. Intenta llegar hasta el parque más cercano.',
                'metros_requeridos' => 2000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 80,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Caminante dedicado',
                'descripcion'      => 'Completa 3 kilómetros a pie. ¡Una buena forma de despejar la mente!',
                'metros_requeridos' => 3000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 120,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Ruta exprés',
                'descripcion'      => 'Cubre 4 kilómetros en un único paseo. ¡Un reto para los más activos!',
                'metros_requeridos' => 4000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 160,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Caminar 500 metros',
                'descripcion'      => 'Camina al menos 500 metros para completar esta misión.',
                'metros_requeridos' => 500,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 30,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Descubridor de calles',
                'descripcion'      => 'Explora 1,2 km por calles que no hayas recorrido antes. ¡Descubre tu ciudad!',
                'metros_requeridos' => 1200,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => false,
                'puntos'           => 55,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ─── SEMANALES ──────────────────────────────────────────────
            [
                'nombre'           => 'Media maratón urbana',
                'descripcion'      => 'Recorre 5 kilómetros durante la semana. ¡Un gran reto para tu semana!',
                'metros_requeridos' => 5000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 200,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Gran explorador',
                'descripcion'      => 'Camina 8 kilómetros esta semana. ¡Cada paso cuenta!',
                'metros_requeridos' => 8000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 300,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Reto de los 10K',
                'descripcion'      => 'Recorre 10 kilómetros esta semana. ¡Demuestra tu constancia!',
                'metros_requeridos' => 10000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 400,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Velocista de la semana',
                'descripcion'      => 'Alcanza los 15 kilómetros esta semana. ¡Un reto para los más activos!',
                'metros_requeridos' => 15000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 600,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Maratonista urbano',
                'descripcion'      => 'Recorre 20 kilómetros en una semana. ¡El reto definitivo!',
                'metros_requeridos' => 20000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 1000,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Conquistador de barrios',
                'descripcion'      => 'Camina 6 kilómetros esta semana por distintos barrios de tu ciudad.',
                'metros_requeridos' => 6000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 250,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Paseo de Barcelona',
                'descripcion'      => 'Acércate al Passeig de Gràcia y disfruta de su arquitectura única.',
                'metros_requeridos' => 500,
                'ejeX'             => 41.3917,
                'ejeY'             => 2.1649,
                'direccion'        => 'Passeig de Gràcia, Barcelona',
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 350,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'La Barceloneta',
                'descripcion'      => 'Visita la playa de la Barceloneta y respira el aire del Mediterráneo.',
                'metros_requeridos' => 300,
                'ejeX'             => 41.3795,
                'ejeY'             => 2.1893,
                'direccion'        => 'Playa de la Barceloneta, Barcelona',
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 400,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Parc de la Ciutadella',
                'descripcion'      => 'Llega al Parc de la Ciutadella y disfruta de su naturaleza en el corazón de Barcelona.',
                'metros_requeridos' => 200,
                'ejeX'             => 41.3863,
                'ejeY'             => 2.1869,
                'direccion'        => 'Parc de la Ciutadella, Barcelona',
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 500,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'nombre'           => 'Semana activa',
                'descripcion'      => 'Camina al menos 3 km en total durante la semana. ¡Mantén el ritmo!',
                'metros_requeridos' => 3000,
                'ejeX'             => null,
                'ejeY'             => null,
                'direccion'        => null,
                'premium'          => false,
                'semanal'          => true,
                'puntos'           => 180,
                'evento_id'        => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
        ];

        // Solo insertar misiones que no existan ya (por nombre)
        foreach ($misiones as $mision) {
            $exists = DB::table('misiones')
                ->where('nombre', $mision['nombre'])
                ->where('evento_id', null)
                ->exists();

            if (!$exists) {
                DB::table('misiones')->insert($mision);
            }
        }
    }

    public function down(): void
    {
        $nombres = [
            'Primer paso del día', 'Paseo matutino', 'Media hora andando',
            'El kilómetro diario', 'Explorador urbano', 'Ruta al parque',
            'Caminante dedicado', 'Ruta exprés', 'Descubridor de calles',
            'Media maratón urbana', 'Gran explorador', 'Reto de los 10K',
            'Velocista de la semana', 'Maratonista urbano', 'Conquistador de barrios',
            'Paseo de Barcelona', 'La Barceloneta', 'Parc de la Ciutadella',
            'Semana activa',
        ];

        DB::table('misiones')->whereIn('nombre', $nombres)->delete();
    }
};
